### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'â€”'

### ISSUE THREAD

**Issue by clau-bucur** [cytech/Home-Assistant-wundergroundpws#173]
**Describe the bug**
Using v2.0.1 manually installed.
Added the integration from UI and checked "Create forecast sensors" afterwards I enabled my sensors of interest.

My log is filled with the following error, while processing forecast_temperature_0d.

**Error log**
```2023-05-25 22:37:29.887 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'â€”'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 204, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 349, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 146, in async_update_listeners
    update_callback()
  File "/config/custom_components/wundergroundpws/sensor.py", line 200, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.xxxxx_forecast_temperature_0d has device class temperature, state class None unit Â°C and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: â€” (<class 'str'>)
```

**To Reproduce**
1. Install component
2. Add integration with a WU key
3. Watch the errors if they appear

**Expected behavior**
The component handles invalid data, or somehow that errors are not present in the logs.

**Comment by cytech** [comment]
fixed v2.0.2
