### ISSUE TITLE
Entities stopped updating, cannot create on re-setup

### ISSUE THREAD

**Issue by lessthanjoey** [cytech/Home-Assistant-wundergroundpws#208]
Description:
Previously working wundergroundpws integration entities were not being updated after updating to 2.0.4 from 2.0.3 and restarting home assistant (initially on 2023.9.2, since tried 2023.9.3 and 2023.10.0). 
- Checked entities directly and they were listed as no longer being provided.
- Removed entities and config for integration, re-added pws for the integration and received errors like the following in logs:
```
Logger: custom_components.wundergroundpws.coordinator
Source: custom_components/wundergroundpws/coordinator.py:155
Integration: Wundergroundpws ([documentation](https://github.com/cytech/Home-Assistant-wundergroundpws/), [issues](https://github.com/cytech/Home-Assistant-wundergroundpws/issues/))
First occurred: 4:17:14 PM (3 occurrences)
Last logged: 4:27:38 PM

Error fetching WUnderground data: ContentTypeError(RequestInfo(url=URL('https://api.weather.com/v3/wx/forecast/daily/5day?geocode=<redact>&language=en-US&format=json&apiKey=<redact>&units=e'), method='GET', headers=<CIMultiDictProxy('Host': 'api.weather.com', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36', 'Accept-Encoding': 'gzip', 'Accept': '*/*')>, real_url=URL('https://api.weather.com/v3/wx/forecast/daily/5day?geocode=<redact>&language=en-US&format=json&apiKey=<redact>&units=e')), (), message='Attempt to decode JSON with unexpected mimetype: application/octet-stream', headers=<CIMultiDictProxy('Content-Length': '5518', 'Content-Type': 'application/octet-stream', 'X-Region': 'us-west-2', 'Strict-Transport-Security': 'max-age=86400', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'none'", 'X-Trace-Token': '67a3a637-ce49-414c-a3a6-37ce49714c34', 'trace-name': 'v3includerouter', 'Access-Control-Allow-Origin': '*', 'Surrogate-Control': 'ESI/1.0', 'Cache-Control': 'max-age=492', 'Date': 'Wed, 04 Oct 2023 23:17:14 GMT', 'Connection': 'keep-alive')>)
```
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:359
Integration: Sensor (documentation, issues)
First occurred: 4:17:14 PM (2 occurrences)
Last logged: 4:27:39 PM

Error while setting up wundergroundpws platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/wundergroundpws/sensor.py", line 46, in async_setup_entry
    sensors = [
              ^
  File "/config/custom_components/wundergroundpws/sensor.py", line 47, in <listcomp>
    WundergroundPWSSensor(coordinator, description) for description in SENSOR_DESCRIPTIONS
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wundergroundpws/sensor.py", line 116, in __init__
    self._sensor_data = _get_sensor_data(
                        ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wundergroundpws/sensor.py", line 180, in _get_sensor_data
    return sensors[FIELD_OBSERVATIONS][0][kind]
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```
```
Logger: homeassistant.components.weather
Source: helpers/entity_platform.py:507
Integration: Weather (documentation, issues)
First occurred: 4:17:14 PM (2 occurrences)
Last logged: 4:27:39 PM

Error adding entities for domain weather with platform wundergroundpws
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 820, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 785, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 936, in state
    return self.condition
           ^^^^^^^^^^^^^^
  File "/config/custom_components/wundergroundpws/weather.py", line 163, in condition
    day = self.coordinator.get_forecast(FIELD_FORECAST_ICONCODE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wundergroundpws/coordinator.py", line 214, in get_forecast
    return self.data[FIELD_DAYPART][0][field][period]
           ~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```
```
Logger: homeassistant.components.weather
Source: helpers/entity_platform.py:367
Integration: Weather (documentation, issues)
First occurred: 4:17:14 PM (2 occurrences)
Last logged: 4:27:39 PM

Error while setting up wundergroundpws platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 820, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 785, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 936, in state
    return self.condition
           ^^^^^^^^^^^^^^
  File "/config/custom_components/wundergroundpws/weather.py", line 163, in condition
    day = self.coordinator.get_forecast(FIELD_FORECAST_ICONCODE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wundergroundpws/coordinator.py", line 214, in get_forecast
    return self.data[FIELD_DAYPART][0][field][period]
           ~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

After this, to recreate I:
- removed the integration
- removed all entities
- deleted installation directory (custom_components/wundergroundpws)
- installed 2.0.3 (since that had been working previously)
- re-setup integration
- same issue as above
- repeated, but moved back to 2.0.4
- repeated, but upgraded to home-assistant 2023.9.3
- repeated, but upgraded to home-assistant 2023.10.0
- regenerated API keys with wunderground and repeated.

It seems that it all comes down to being unable to parse the API data properly based on the first log excerpt above, but I don't know why that's happening or if it's coincidental with my version upgrades.

Thanks in advance.

**Comment by inguy24** [comment]
I have the exact same error with the same log outputs. It seems to correspond to updating to new core 23.10 but could be coincidence.

**Comment by lessthanjoey** [comment]
> I have the exact same error with the same log outputs. It seems to correspond to updating to new core 23.10 but could be coincidence.

It definitely happened to me while still on 2023.9.2, might be unrelated to the updates and instead a change on wunderground's side, etc?

**Comment by cytech** [comment]
wunderground api issue
see
https://github.com/cytech/Home-Assistant-wundergroundpws/discussions/207

**Comment by lessthanjoey** [comment]
working again for me today too, thanks.
