### ISSUE TITLE
Error while setting up wundergroundpws platform for weather - FIELD_FORECAST_ICONCODE

### ISSUE THREAD

**Issue by clau-bucur** [cytech/Home-Assistant-wundergroundpws#215]
**Describe the bug**
Integration is no longer working, for a few days.
All entites are unavailable.

Looking at in the logs, I have:
```
2023-12-08 16:45:25.758 ERROR (MainThread) [custom_components.wundergroundpws.coordinator] Check WUnderground API ('NO CURRENT RESULT',)
2023-12-08 16:45:25.761 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up wundergroundpws platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/wundergroundpws/sensor.py", line 46, in async_setup_entry
    sensors = [
              ^
  File "/config/custom_components/wundergroundpws/sensor.py", line 47, in <listcomp>
    WundergroundPWSSensor(coordinator, description) for description in SENSOR_DESCRIPTIONS
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wundergroundpws/sensor.py", line 116, in __init__
    self._sensor_data = _get_sensor_data(
                        ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wundergroundpws/sensor.py", line 180, in _get_sensor_data
    return sensors[FIELD_OBSERVATIONS][0][kind]
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2023-12-08 16:45:25.768 ERROR (MainThread) [homeassistant.components.weather] Error adding entities for domain weather with platform wundergroundpws
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 754, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1025, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 745, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 751, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 973, in state
    return self.condition
           ^^^^^^^^^^^^^^
  File "/config/custom_components/wundergroundpws/weather.py", line 163, in condition
    day = self.coordinator.get_forecast(FIELD_FORECAST_ICONCODE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wundergroundpws/coordinator.py", line 214, in get_forecast
    return self.data[FIELD_DAYPART][0][field][period]
           ~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2023-12-08 16:45:25.774 ERROR (MainThread) [homeassistant.components.weather] Error while setting up wundergroundpws platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 369, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 754, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1025, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 745, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 751, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 973, in state
    return self.condition
           ^^^^^^^^^^^^^^
  File "/config/custom_components/wundergroundpws/weather.py", line 163, in condition
    day = self.coordinator.get_forecast(FIELD_FORECAST_ICONCODE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wundergroundpws/coordinator.py", line 214, in get_forecast
    return self.data[FIELD_DAYPART][0][field][period]
           ~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

```

**Comment by cytech** [comment]
error indictes wunderground api is not available
2023-12-08 16:45:25.758 ERROR (MainThread) [custom_components.wundergroundpws.coordinator] Check WUnderground API ('NO CURRENT RESULT',)

**Comment by clau-bucur** [comment]
It should be available as the weather station is working just fine.
Could you give me some hints on what to check?

**Comment by cytech** [comment]
i suppose it is possible you entered the stationid or api key incorrectly.
Enter your Weather Underground API key and your Station ID (Case Sensitive. Must match the ID of your Wunderground device)
and submit.
unfortunately you cant edit these from the integration so you would need to remove it and reinstall it if thats the case.
or manually check/edit the wundergroundpws entry  in .storage/core.config_entries.
or try to access the api thru browser and see if you get a result
https://api.weather.com/v2/pws/observations/current?stationId=[deviceID]&format=json&units=m&numericPrecision=decimal&apiKey=[API-key]

**Comment by cytech** [comment]
by not filing a proper "bug" report, and no other issues exist, i dont know what to tell you.
what version home assistant?
what version wundergroundpws?
the latest home assistant require v2.04 of the wunderground integration
take this to a discussion
https://github.com/cytech/Home-Assistant-wundergroundpws/discussions/217

**Comment by clau-bucur** [comment]
Understood. I apologise for the lack of details. I'm gonna follow up on that discussion.
JFYI:
HA 2023.12.0
wundergroundpws 2.0.4
