### ISSUE TITLE
After couple of days I lose connection to Wunderground data, after restarting HA, everything is OK, for a couple of days

### ISSUE THREAD

**Issue by Videodok** [cytech/Home-Assistant-wundergroundpws#230]
After a couple of days I loose connection to WUnderground, when rebooting HA, I regain connection without any issues, but then connection is lost after a couple of days again.

![Screenshot 2024-01-28 095056](https://github.com/cytech/Home-Assistant-wundergroundpws/assets/107343349/8b4dabef-f64d-41fe-ac4c-584a8eb706b7)

Running 2.05 on HA Yellow, 

Core 2024.1.5
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

Home assistant laog

2024-01-28 09:46:49.091 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration wundergroundpws which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-01-28 09:47:09.364 DEBUG (MainThread) [custom_components.wundergroundpws.coordinator] Finished fetching WundergroundPWSUpdateCoordinator data in 4.208 seconds (success: True)

2024-01-28 09:47:17.949 WARNING (MainThread) [homeassistant.components.weather] wundergroundpws::WUWeather implements the `forecast` property or sets `self._attr_forecast` in a subclass of WeatherEntity, this is deprecated and will be unsupported from Home Assistant 2024.3. Please create a bug report at https://github.com/cytech/Home-Assistant-wundergroundpws/issues/

2024-01-28 09:47:17.951 ERROR (MainThread) [homeassistant.components.weather] Error adding entities for domain weather with platform wundergroundpws
Traceback (most recent call last):
  File "/config/custom_components/wundergroundpws/weather.py", line 138, in native_visibility
    return self._attr_visibility
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WUWeather' object has no attribute '_attr_visibility'
2024-01-28 09:47:17.975 ERROR (MainThread) [homeassistant.components.weather] Error while setting up wundergroundpws platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1282, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 788, in state_attributes
    if (visibility := self.native_visibility) is not None:
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wundergroundpws/weather.py", line 138, in native_visibility
    return self._attr_visibility
           ^^^^^^^^^^^^^^^^^^^^^
2024-01-28 09:52:17.511 DEBUG (MainThread) [custom_components.wundergroundpws.coordinator] Finished fetching WundergroundPWSUpdateCoordinator data in 0.422 seconds (success: True)
2024-01-28 09:52:17.526 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):

  File "/config/custom_components/wundergroundpws/weather.py", line 138, in native_visibility
    return self._attr_visibility
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WUWeather' object has no attribute '_attr_visibility'

**Comment by jaymoore962** [comment]
i have the same issue and i need it fixed asap because we relay on this addon so we know what the weather is

**Comment by hansaplast26** [comment]
same here

**Comment by lolo51530** [comment]
IDEM

**Comment by MazzMat** [comment]
Me too

**Comment by Longlife2012** [comment]
Same Problems.

Is there a fix available???

**Comment by Johndowne** [comment]
Same issue - is there some way to reduce API hits if that is the issue?

**Comment by Rmh1978** [comment]
I had the same issue, then i updated and it fixed the issue. I hadent added the repo in Hacs so i did not get automatic updates through HA.

**Comment by cytech** [comment]
make sure you are running wundergroundpws v2.0.6.
as far as api calls go,
Note that every station instance requires it's own set of API calls, so be aware of exceeding the Weather Underground Personal API rate limit (which i think is 1000 per day).
Each instance calls every 5 minutes or 288 times a day.
plus where ever else you are calling it from (Kodi weather for example)
you can manually edit the coordinator.py file in the wundergroundpws directory and change the line:

MIN_TIME_BETWEEN_UPDATES = timedelta(minutes=5)
