### ISSUE TITLE
Integration stopped loading.

### ISSUE THREAD

**Issue by smarthomeaf** [cytech/Home-Assistant-wundergroundpws#234]
Integrations stopped loading today.   (have multiple Home assistance instances and it stopped on all).  Tried to manually relaod with no luck.  

It is still actively reporting on weather underground

<img width="828" alt="image" src="https://github.com/cytech/Home-Assistant-wundergroundpws/assets/105226208/9f79f60d-3c3d-4078-b260-29331ac93ca1">

Here is my Hass version

<img width="399" alt="image" src="https://github.com/cytech/Home-Assistant-wundergroundpws/assets/105226208/b17f9728-bc2a-4874-a6bf-d305bfff1773">

Here is the debug log.

```
Logger: homeassistant.components.weather
Source: helpers/entity_platform.py:352
Integration: Weather (documentation, issues)
First occurred: 5:33:47 PM (3 occurrences)
Last logged: 5:44:36 PM

Error while setting up wundergroundpws platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 352, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 782, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1325, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1047, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 995, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 1000, in state
    return self.condition
           ^^^^^^^^^^^^^^
  File "/config/custom_components/wundergroundpws/weather.py", line 163, in condition
    day = self.coordinator.get_forecast(FIELD_FORECAST_ICONCODE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wundergroundpws/coordinator.py", line 214, in get_forecast
    return self.data[FIELD_DAYPART][0][field][period]
           ~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by smarthomeaf** [comment]
Looks like my API expired.   The weird thing is that it expired in September of 2023 and yet it was still working until today.
