### ISSUE TITLE
ValueError: Sensor has device class 'None', state class 'None' unit '' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value:

### ISSUE THREAD

**Issue by barto64** [cytech/Home-Assistant-wundergroundpws#237]
IF YOU ARE NOT REPORTING A REPRODUCIBLE BUG, PLEASE USE DISCUSSIONS
**Describe the bug**
I am getting hundred of times the below error message creating thousand of error lines in the HA log.

ValueError: Sensor sensor.itresc20_forecast_summary_0d has device class 'None', state class 'None' unit '' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value:

**To Reproduce**
Steps to reproduce the behavior: If you configere the integration using my station "itresc20" you should get the same error.

**Expected behavior**
Same as for all other forecast summary sensors, none of them producde any error but the one "sensor.itresc20_forecast_summary_0d".

**Desktop (please complete the following information):**
Home Assistant Blue / Hardkernel ODROID-N2/N2+
 Core 2024.3.1
Supervisor 2024.03.0
Operating System 12.1
Frontend 20240307.0

Wunderground integration version: "version": "2.0.6",

**Additional context**
Registrador: homeassistant
Fuente: components/sensor/__init__.py:670
Ocurrió por primera vez: 21 de marzo de 2024, 03:19:01 (239 ocurrencias)
Último inicio de sesión: 11:14:03

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 668, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'Chubascos matinales. Máxima de 24 C. Vientos del NE de 10 a 15 km/h. 30% probab. de lluvia.'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 261, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 417, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
    update_callback()
  File "/config/custom_components/wundergroundpws/sensor.py", line 200, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 992, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1050, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 670, in state
    raise ValueError(
ValueError: Sensor sensor.itresc20_forecast_summary_0d has device class 'None', state class 'None' unit '' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Chubascos matinales. Máxima de 24 C. Vientos del NE de 10 a 15 km/h. 30% probab. de lluvia.' (<class 'str'>)

![image](https://github.com/cytech/Home-Assistant-wundergroundpws/assets/47034221/3fe86431-b5ad-4292-a796-eda014720316)

**Comment by rct** [comment]
I have the same issue.  So far not finding any workarounds other than disabling that entity.

**Comment by rct** [comment]
Maybe a clue, maybe not.

I only get errors for `sensor.knywesth29_forecast_summary_0d`

I have these enabled:

* `sensor.knywesth29_forecast_summary_0d`
* `sensor.knywesth29_forecast_summary_1n`
* `sensor.knywesth29_forecast_summary_2d`

The difference between them looking at `.storage/core.entity_registry` is that:

* 0d - the one that triggers the ValueError has `"unit_of_measurement":""`
* 1n and 2d, which don't trigger an error, both have `"unit_of_measurement":null`

**Comment by clau-bucur** [comment]
Same issue here: `ValueError: Sensor sensor.ic3_forecast_summary_0d has device class 'None', state class 'None' unit '' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'A mix of clouds and sun. Turning cooler. High 26C. Winds SW at 15 to 30 km/h.' (<class 'str'>)`

Complete error:
```
2024-04-16 03:41:41.375 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 668, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'A mix of clouds and sun. Turning cooler. High 26C. Winds SW at 15 to 30 km/h.'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 414, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/wundergroundpws/sensor.py", line 200, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1119, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1056, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1004, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 670, in state
    raise ValueError(
ValueError: Sensor sensor.ic3_forecast_summary_0d has device class 'None', state class 'None' unit '' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'A mix of clouds and sun. Turning cooler. High 26C. Winds SW at 15 to 30 km/h.' (<class 'str'>)
```

**Comment by barto64** [comment]
> I have the same issue. So far not finding any workarounds other than disabling that entity.
> 
> It seems like this was previously reported in #211, but closed as not reproducible.
> 
> Here's the most recent entriy from my log
> 
> ```
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 668, in state
>     numerical_value = float(value)  # type:ignore[arg-type]
>                       ^^^^^^^^^^^^
> ValueError: could not convert string to float: 'Rain showers along with windy conditions. High 54F. Winds W at 20 to 30 mph. Chance of rain 50%.  Winds could occasionally gust over 40 mph.'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
>     await self._async_refresh(log_failures=True, scheduled=True)
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 414, in _async_refresh
>     self.async_update_listeners()
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
>     update_callback()
>   File "/config/custom_components/wundergroundpws/sensor.py", line 200, in _handle_coordinator_update
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1119, in _async_write_ha_state
>     state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
>                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1056, in __async_calculate_state
>     state = self._stringify_state(available)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1004, in _stringify_state
>     if (state := self.state) is None:
>                  ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 670, in state
>     raise ValueError(
> ValueError: Sensor sensor.knywesth29_forecast_summary_0d has device class 'None', state class 'None' unit '' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Rain showers along with windy conditions. High 54F. Winds W at 20 to 30 mph. Chance of rain 50%.  Winds could occasionally gust over 40 mph.' (<class 'str'>)
> ```
> 
> Here's the data about that entity from `.store/core.entity_registry` in case it helps:
> 
> ```
> {
>   "aliases": [],
>   "area_id": "weather",
>   "categories": {},
>   "capabilities": null,
>   "config_entry_id": "6eab553895a06c8d6f1eb2aca7fb05f3",
>   "device_class": null,
>   "device_id": null,
>   "disabled_by": null,
>   "entity_category": null,
>   "entity_id": "sensor.knywesth29_forecast_summary_0d",
>   "hidden_by": null,
>   "icon": null,
>   "id": "e19cf99ce1e6ee9a4f9894b5925c5bbd",
>   "has_entity_name": true,
>   "labels": [],
>   "name": null,
>   "options": {
>     "cloud.alexa": {
>       "should_expose": false
>     },
>     "cloud.google_assistant": {
>       "should_expose": false
>     },
>     "conversation": {
>       "should_expose": false
>     }
>   },
>   "original_device_class": null,
>   "original_icon": "mdi:gauge",
>   "original_name": "Forecast Summary Today Expired",
>   "platform": "wundergroundpws",
>   "supported_features": 0,
>   "translation_key": null,
>   "unique_id": "knywesth29,narrative_0fdp",
>   "previous_unique_id": null,
>   "unit_of_measurement": ""
> }
> ```

Not sure what station our friend @cytech used in trying to reproduce the issue, I offer mine to him for testing, it is ITRESC20

**Comment by cytech** [comment]
this is an artifact from v2.0.0 corrected in v2.0.2..
it only hits this forecast sensor because of wunderground api returning null after 3:00 pm.
options you can try:
1.)
(not positive this will take..)
shut down home assistant.
manually edit the .storage/core.entity_registry as mentioned by @rct above.
change the line containing "sensor.<STATION_ID>_forecast_summary_0d" unit_of_measurement value from "" to null.
restart home assistant.
or
2.)
in homeassistant go to devices, wundergroundpws, configure, and turn off "Create Forecast Sensors"
show wundergroundpws entities, search for "sensor.<STATION_ID>_forecast_summary_0d"
enter selection mode and select that sensor and remove it.
go back to devices, wundergroundpws, configure, and turn on "Create Forecast Sensors"
go back to wundergroundpws entities, search for "sensor.<STATION_ID>_forecast_summary_0d" and enable it and reenable any others that you had enabled and became disabled...
or
3.)
completely remove the wundergroundpws integration as described here https://github.com/cytech/Home-Assistant-wundergroundpws?tab=readme-ov-file#upgrade
particularly the part about removing all wundergroundpws entities.
reinstall the v2.0.6 integration.

if you are using HACS you are on your own....
