### ISSUE TITLE
Wunderground not auto-updating

### ISSUE THREAD

**Issue by McFozzy75** [cytech/Home-Assistant-wundergroundpws#241]
Hello,

The Wunderground intergration is not auto-updating. If I reload the integration I get the last values. In the LOG there's an error. Someone have a idea what the problem is?

> Deze fout is ontstaan door een aangepaste integratie.
> 
> Logger: homeassistant
> Bron: custom_components/wundergroundpws/weather.py:138
> integratie: Wundergroundpws (documentatie, problemen)
> Eerst voorgekomen: 11:46:39 (48 gebeurtenissen)
> Laatst gelogd: 15:47:23
> 
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1504, in _async_process_registry_update_or_remove
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1119, in _async_write_ha_state
>     state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
>                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1058, in __async_calculate_state
>     attr.update(self.state_attributes or {})
>                 ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 691, in state_attributes
>     if (visibility := self.native_visibility) is not None:
>                       ^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/wundergroundpws/weather.py", line 138, in native_visibility
>     return self._attr_visibility
>            ^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'WUWeather' object has no attribute '_attr_visibility'. Did you mean: 'native_visibility'

**Comment by cytech** [comment]
you are not running the latest version of wundergroundpws v2.0.6
not a valid bug report
move to discussions
