### ISSUE TITLE
Spin and not working

### ISSUE THREAD

**Issue by NA7KR** [cytech/Home-Assistant-wundergroundpws#45]
The config test just spins for ever, reboot and does not work no errors

**Comment by NightwoodHass** [comment]
I have the same issue happening since the latest update. 

Prior to the latest update I had this integration working with no issues, however since the update I have been unable to get the integration working. As OP states, the "Check Configuration" just spins and doesn't return error or valid. I have added the new `numeric_precision` setting.

**Tried**:
1. `numeric_precision` of both `none`, `decimal`, and without the setting added
2. Uninstall and re-install
3. Various combinations in `configuration.yaml`

**Configuration.yaml:**
```
  - platform: wundergroundpws
    api_key: <verified>
    pws_id: <verified>
    numeric_precision: none
    monitored_conditions:
      - temp
      - dewpt
      - winddir
      - humidity
      - heatIndex
      - windChill
      - precipTotal
      - precipRate
      - pressure
      - windGust
      - windSpeed

```
**StackTrace**:
Logger: aiohttp.server
Source: util/yaml/loader.py:61
First occurred: February 18, 2021, 9:23:21 AM (1 occurrences)
Last logged: February 18, 2021, 9:23:21 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/core.py", line 29, in post
    errors = await async_check_ha_config_file(request.app["hass"])
  File "/usr/src/homeassistant/homeassistant/config.py", line 877, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 202, in async_check_ha_config_file
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 475, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 480, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/wundergroundpws/sensor.py", line 46, in <module>
    load_config = config.load_yaml_config_file('/home/homeassistant/configuration.yaml')
  File "/usr/src/homeassistant/homeassistant/config.py", line 329, in load_yaml_config_file
    conf_dict = load_yaml(config_path)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 61, in load_yaml
    with open(fname, encoding="utf-8") as conf_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/homeassistant/configuration.yaml'

**Comment by NightwoodHass** [comment]
Further update:

I noticed in my stack trace above that I'm receiving an error `No such file or directory: '/home/homeassistant/configuration.yaml'` and realised that I had updated sensor.py to incorrect value (to fix another issue). After updating again to `load_config = config.load_yaml_config_file('/config/configuration.yaml')` I get the following on attempted restart:

**StackTrace:**
Logger: homeassistant.core
Source: custom_components/wundergroundpws/sensor.py:48
First occurred: 1:40:49 PM (4 occurrences)
Last logged: 1:43:19 PM

Error executing service: <ServiceCall homeassistant.restart (c:f8156ad5fd7bea717a96a23871736484)>
Error executing service: <ServiceCall homeassistant.restart (c:1c729dd3c716869c4d9f22e6ac457179)>
Error executing service: <ServiceCall homeassistant.restart (c:8bf03219ab912c68e95b015f4614efd7)>
Error executing service: <ServiceCall homeassistant.restart (c:c880c4b2676072003250ccb5a637f80e)>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1471, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 415, in async_handle_core_service
    errors = await conf_util.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/config.py", line 877, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 202, in async_check_ha_config_file
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 475, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 480, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/wundergroundpws/sensor.py", line 48, in <module>
    UNIT_SYSTEM = load_config['homeassistant']['unit_system']
KeyError: 'unit_system'

Despite having a unit system set and attempting with both Metric and Imperial saved, I continue to get the error.

**Comment by NA7KR** [comment]
I found this in check_config.txt
[31mFatal error while loading config:[0m [Errno 2] No such file or directory: '/root/.homeassistant/configuration.yaml'
[01;37mFailed config[0m
  [01;31mGeneral Errors:[0m [31m[31m
    - [Errno 2] No such file or directory: '/root/.homeassistant/configuration.yaml'
[0m
How do I fix it?

**Comment by NightwoodHass** [comment]
@NA7KR There's a known issue with sensor.py documented [here](https://github.com/cytech/Home-Assistant-wundergroundpws/issues/1) with two solutions.

**Comment by NA7KR** [comment]
Also getting this error now  /usr/src/homeassistant/ is not present

Log Details (ERROR)
Logger: aiohttp.server
Source: custom_components/wundergroundpws/sensor.py:48
First occurred: 10:28:04 PM (1 occurrences)
Last logged: 10:28:04 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/core.py", line 29, in post
    errors = await async_check_ha_config_file(request.app["hass"])
  File "/usr/src/homeassistant/homeassistant/config.py", line 877, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 202, in async_check_ha_config_file
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 475, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 480, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/wundergroundpws/sensor.py", line 48, in <module>
    UNIT_SYSTEM = load_config['homeassistant']['unit_system']
KeyError: 'homeassistant'

**Comment by cytech** [comment]
See issue #46
