### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by justinmaiuto** [cytech/Home-Assistant-wundergroundpws#98]
Integration errors on startup

2022-05-01 22:46:27 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up wundergroundpws platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/wundergroundpws/sensor.py", line 401, in async_setup_platform
await rest.async_update()
File "/config/custom_components/wundergroundpws/sensor.py", line 551, in async_update
with async_timeout.timeout(10, loop=self._hass.loop):
TypeError: timeout() got an unexpected keyword argument 'loop'

**To Reproduce**
Start home assistant

**Expected behavior**
Integration starts without error

**Desktop (please complete the following information):**
Home Assistant 2022.4.7

**Additional context**
Detected code that called async_timeout.timeout with loop keyword argument. The loop keyword argument is deprecated and calls will fail after Home Assistant 2022.2.

**Comment by justinmaiuto** [comment]
Looks like a fix similar to this needs to be implemented?

https://github.com/home-assistant/core/pull/69304

**Comment by cytech** [comment]
see #97

**Comment by cytech** [comment]
This issue was closed because it has been stale for 60 days with no activity.
